// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mangos.services.CoupanAPI.Data;

#nullable disable

namespace mangos.services.CoupanAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250517065906_addedCouponData")]
    partial class addedCouponData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mangos.services.CoupanAPI.Models.coupan", b =>
                {
                    b.Property<int>("coupanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("coupanId"));

                    b.Property<string>("coupanCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("discountAmount")
                        .HasColumnType("float");

                    b.Property<int>("minAmount")
                        .HasColumnType("int");

                    b.HasKey("coupanId");

                    b.ToTable("Coupans");

                    b.HasData(
                        new
                        {
                            coupanId = 1,
                            coupanCode = "10OFF",
                            discountAmount = 10.0,
                            minAmount = 20
                        },
                        new
                        {
                            coupanId = 2,
                            coupanCode = "20OFF",
                            discountAmount = 20.0,
                            minAmount = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
