// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mangos.services.ShoppingCartAPI.Data;

#nullable disable

namespace mangos.services.ShoppingCartAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250619030958_cartHeaderDetails")]
    partial class cartHeaderDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mangos.services.ShoppingCartAPI.Models.CartDetails", b =>
                {
                    b.Property<int>("cartDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cartDetailsId"));

                    b.Property<int>("cartHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("count")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.HasKey("cartDetailsId");

                    b.HasIndex("cartHeaderId");

                    b.ToTable("cartDeatails");
                });

            modelBuilder.Entity("mangos.services.ShoppingCartAPI.Models.CartHeader", b =>
                {
                    b.Property<int>("cartHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cartHeaderId"));

                    b.Property<string>("coupanCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cartHeaderId");

                    b.ToTable("cartHeaders");
                });

            modelBuilder.Entity("mangos.services.ShoppingCartAPI.Models.CartDetails", b =>
                {
                    b.HasOne("mangos.services.ShoppingCartAPI.Models.CartHeader", "cardHeader")
                        .WithMany()
                        .HasForeignKey("cartHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cardHeader");
                });
#pragma warning restore 612, 618
        }
    }
}
